name: 'Stop Hardhat Node'
description: 'Stops a running Hardhat node by PID'
inputs:
  pid:
    description: 'Process ID of the hardhat node to stop'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Stop Hardhat node
      shell: bash
      run: |
        # Get PID from input or fallback to file
        HARDHAT_PID="${{ inputs.pid }}"
        if [ -z "$HARDHAT_PID" ] && [ -f /tmp/hardhat.pid ]; then
          HARDHAT_PID=$(cat /tmp/hardhat.pid)
        fi
        
        if [ -n "$HARDHAT_PID" ]; then
          echo "Stopping Hardhat node (PID: $HARDHAT_PID)..."
          kill $HARDHAT_PID 2>/dev/null || true
          # Wait a bit for graceful shutdown
          sleep 2
          # Force kill if still running
          kill -9 $HARDHAT_PID 2>/dev/null || true
          echo "Hardhat node stopped"
          rm -f /tmp/hardhat.pid
        else
          echo "No PID found, skipping cleanup"
        fi

